typography_spectrum: 0.6988215996490529
content_rating:
  adult: false
color:
  brandColors:
    - '#DC3522'
    - '#D9CB9E'
    - '#374140'
    - '#2A2C2B'
    - '#1E1E20'
  brandStrength: 0.588594152262036
  lightness: 0.5801064812537647
  saturation: 0.8190932167627352
  rhythmicContrast: 0.8591251188063183
opengraph:
  type: ''
  appId: ''
layout_spectrum: 0.8091125996867542
author:
  name: ''
  url: ''
  email: ''
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/02bf0e4e-07e6-4e98-afe2-cb0c0cf912a7.jpg
name: 'Tankette #451'
navigation:
  - name: BCRD
    url: 'http://bearcityrollerderby.com/en/'
    type: external
  - name: My derby kisses
    id: 43ed3121-659a-4777-8f99-24bf6d089422
    type: content
title: ''
